server:
  port: 8088

spring:
  application:
    name: proposal-java-service

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

# 日志
logging:
  level:
    com.ccdc.proposal: DEBUG
    org.springframework.web: INFO
